apiVersion: apps/v1
kind: Deployment
metadata:
  name: storj01
  annotations:
    component: storagenode
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: storj01
      component: storagenode
  template:
    metadata:
      labels:
        app: storj01
        component: storagenode
      annotations:
        prometheus.io/instance: "storagenode01"
        prometheus.io/scrape: "true"
        prometheus.io/port: "15009"
        prometheus.io/path: /metrics
    spec:
      containers:
        - image: foobar
          imagePullPolicy: IfNotPresent
          name: storj
          ports:
            - containerPort: 28967
              protocol: TCP
            - containerPort: 28967
              protocol: UDP
          args:
            - storagenode
            - run
          volumeMounts:
            - mountPath: /app/config
              name: data
            - mountPath: /app/identity
              name: identitiy
          env:
            - name: STORJ_SERVER_ADDRESS
              value: 0.0.0.0:28967
            - name: STORJ_CONSOLE_ADDRESS
              value: 0.0.0.0:15000
            - name: STORJ_SERVER_PRIVATE_ADDRESS
              value: 0.0.0.0:15002
            - name: STORJ_DEBUG_ADDR
              value: 0.0.0.0:15009
            - name: STORJ_SERVER_USE_PEER_CA_WHITELIST
              value: "false"
            - name: STORJ_HEALTHCHECK_DETAILS
              value: "true"
            - name: STORJ_STORAGE_ALLOCATED_DISK_SPACE
              value: "14T"
            - name: STORJ_PIECES_ENABLE_LAZY_FILEWALKER
              value: "false"
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /storj/storj01/data
        - name: identitiy
          hostPath:
            path: /storj/storj01/identity
