services:
  cockroach:
    labels: 
      app: cockroach
    command:
    - start-single-node
    - --insecure
    - --http-addr=localhost:8086
    - --store="/tmp/cockroach"
    deploy:
      replicas: 1
    image: cockroachdb/cockroach
    ports:
    - mode: ingress
      target: 26257
      published: 26257
